### ISSUE TITLE
milestone/changelog availability

### ISSUE THREAD

**Issue by csrl** [hapijs/hapijs.com#144]
Currently it seems the best place to find changes to Hapi is in the milestone filter, eg.

https://github.com/hapijs/hapi/issues?q=milestone%3A8.1.0

It'd be nice to have the milestones available from http://hapijs.com/updates

**Comment by nlf** [comment]
I like this, maybe it's a better idea to list milestones and their associated issues directly rather than rendering the CHANGELOG.md. This would allow us to not have to rely on the CHANGELOG being kept up to date, as well as making it super easy to link to the milestones from their headers.

Anyone feel like taking this on?

**Comment by hueniverse** [comment]
I would LOVE to get rid of the changlog file and have the latest always sit here.

**Comment by pon** [comment]
What is the current process for updating the CHANGELOG.md file?

**Comment by hueniverse** [comment]
I have to manually run `npm changelog` in hapi and commit the change.

**Comment by mtharrison** [comment]
Happy to take this on along with #171

**Comment by hueniverse** [comment]
@mtharrison both assigned to you now.

**Comment by nlf** [comment]
@mtharrison keep in mind #196 when working on this. would be nice if we had the ability to display changelogs for all the plugins as well, and not just hapi itself.

**Comment by mtharrison** [comment]
I think this is resolved now with changelog updates so closing.

**Comment by AdriVanHoudt** [comment]
only it does not have 9.0 atm because of the cache time
