### ISSUE TITLE
Add a link to hapi.js in Action book

### ISSUE THREAD

**Issue by mtharrison** [hapijs/hapijs.com#166]
Would you consider adding a link to the book that I'm writing? http://manning.com/harrison/

There's also an affiliate program that can be worked out with Manning, whereby the project can gain commissions.

**Comment by hueniverse** [comment]
There are a few ways we can do this. One is to add a books section and list it there along with others in the future. Another is to use a chapter from the book in the tutorials and from that page link to the book where people can learn more. I am sure there are more ideas.

As for the commissions, I don't see a way for us to collect these since that will require someone to receive the funds and deal with taxes, as well as deal with funds in the first place. If Manning wants to donate these funds, they can handle it and then give the money to some related community cause that is setup to receive donations.

**Comment by AdriVanHoudt** [comment]
I would do both. A general page with links to educational materials is helpful. And if the book writer/owner wants to do a PR to the tutorials with a good tutorial and link to the book for further info, I see that as a win win. 
As for the commissions, I would prefer it to go to a good cause (dev/js related) or Hapi Swag ;)

**Comment by mtharrison** [comment]
I'd be very happy to contribute some new tutorial content. For the meanwhile, if we could also have a Books or possibly a more general external learning resources page, as suggested by @AdriVanHoudt, that would be great too. Would you like me to work on a PR for this?

I'll speak to Manning regarding the commissions, it'd be nice to see them go to a good cause.

**Comment by AdriVanHoudt** [comment]
A PR never hurts ;)

**Comment by Marsup** [comment]
Asking beforehand neither ;)

**Comment by AdriVanHoudt** [comment]
true :+1:

**Comment by nlf** [comment]
Personally, I love the idea of an external resources section. It's something that's been brought up in the past by people looking for somewhere to link to gists and the like. I also really like the idea of having a tutorial that links to the book. Let me know what I can do to facilitate your PR :+1:

**Comment by nlf** [comment]
Note, see #119 for additional thoughts

**Comment by mtharrison** [comment]
Thanks @nlf. I'll put something together this weekend.

**Comment by nlf** [comment]
this is merged and the link is added, thanks again @mtharrison

**Comment by mtharrison** [comment]
Brilliant, thank you for that!
