### ISSUE TITLE
Move changelog generation to site

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapijs.com#171]
Remove the changelog.md in hapi and generate it by the site every time there is a new release. Also, need to change the changes page layout to not center the changes to make it easier to read it.

**Comment by nlf** [comment]
to do this, we basically need a server method to fetch a list of closed milestones, and a second server method to turn a closed milestone into a changelog entry (will have to look at how mdchangelog does this).

the first server method should have a relatively short cache, maybe every 15 minutes or so, and the second should have a very long cache (like a year) since that data should never change after the milestone is closed and the issues are parsed.

we would then remove the fetching of the changelog.md file and instead dynamically populate the changelog based on data from the above methods. if anyone decides to take a shot at this and has any questions, feel free to post them here :)

**Comment by AdriVanHoudt** [comment]
Won't we hit the github API limit with fetching it evrytime?

**Comment by nlf** [comment]
it doesn't get fetched every time, only when the caching expires, and only one api call will be getting made each time it expires. the generation of changelog segments based on milestones should be cached for a *very* long time. the server makes authenticated requests, so we're allowed a few thousand requests per hour. should be just fine.

**Comment by AdriVanHoudt** [comment]
Ah like that yeah if I have time I'll take a look at it (probably not this
weekend though)

**Comment by mtharrison** [comment]
@AdriVanHoudt Still planning on looking at this? If not, I might like to take a stab.

**Comment by mtharrison** [comment]
I notice the formatting of the changelog on the site is all messed up (http://hapijs.com/updates). This is because the way this commit message is converted to HTML:

    - [**#73**](https://github.com/hapijs/qs/issues/73) Property 'hasOwnProperty' of object #<Object> is not a function

It's swallowing up the following lists. Is that part of the motivation for this change?

**Comment by AdriVanHoudt** [comment]
tbh not to much time atm, I do offer my help if you need it though!

**Comment by diffsky** [comment]
For what it's worth, I've added a `--sanitize` option to `mdchangelog@0.8.0`. That should clean up the list output.

As for the hapijs site, why not make use of the existing mdchangelog package and run it as a job out of bounds of the site serving? `text-align:left` the changelog `div` then get on with more important things?

**Comment by mtharrison** [comment]
That could potentially be done using a cached server method to run mdchangelog as a child process and collect output from stdout using `--stdout` option. We'd still need to take care of md => html conversion on our end.

Still, the benefit of building the changelog markup ourselves from the Github API are:
- Greater control over appearance
- No need for external tools/child processes
- Remove the extra md => html stage by just using hapi's built in template rendering from the API data
- Easier to change stuff in future within scope of Github API

@hueniverse @nlf any thoughts? I'm not sure what the background for this change was.

**Comment by AdriVanHoudt** [comment]
Yeah then I would go with custom markup, if we may we can borrow some ideas from mdchangelog :P
