### ISSUE TITLE
Some sub-updates don't show

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/hapijs.com#223]
see hapijs.com/updates the 9.0 milestone 
![](http://puu.sh/jyAz0/ab7a904e46.png)
![](http://puu.sh/jyAzD/3dc019d5d1.png)

**Comment by mtharrison** [comment]
The content one is because 1.0.2 is still open: https://github.com/hapijs/content/milestones
The subtext one is because it should be `to x.x.x from x.x.x`

We could address both issues maybe by:

 - Include still open milestones for deps (maybe we shouldn't do this though. If it's been released I'm guessing milestone should be closed)
 - Expand the regex to capture this pattern if it's a common one

**Comment by AdriVanHoudt** [comment]
opened https://github.com/hapijs/content/issues/6
and I guess it would be nice to allow `from ... to ...` and `to ... from ...` seems logical

**Comment by mtharrison** [comment]
I updated the regex in a PR
![screen shot 2015-08-12 at 10 00 51](https://cloud.githubusercontent.com/assets/916064/9220258/12848a42-40d9-11e5-92ee-c69d6381dcc6.png)

**Comment by AdriVanHoudt** [comment]
:+1:

**Comment by AdriVanHoudt** [comment]
Content should be fixed now, milestone was closed

**Comment by hueniverse** [comment]
Is this resolved?

**Comment by AdriVanHoudt** [comment]
#224 should have yes (not tested)

**Comment by hueniverse** [comment]
Please close when confirmed.

**Comment by Marsup** [comment]
I've redeployed the site, is it fixed ?

**Comment by mtharrison** [comment]
Looks fixed. Thanks.
