### ISSUE TITLE
Modules API area

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapijs.com#227]
We need each module to have a new API.md file and the site to automatically render those under the /api area (within or under /api/module). This is critical now that the inert, vision, and h2o2 docs are no longer available on the site.

**Comment by AdriVanHoudt** [comment]
Would including the readme also not be helpful? (since in most cases the api.md will be the readme?)

**Comment by hueniverse** [comment]
Hence my suggestion to move all that to a new API.md file

**Comment by AdriVanHoudt** [comment]
I saw the discuss issue afterwards ^^ but why not just use the readme's instead of moving to api.md?

**Comment by hueniverse** [comment]
Because the readme includes all sorts of other crap.

**Comment by devinivy** [comment]
For simple APIs, it's nice for the APIs to be inline in the readme for ease-of-use.  It also puts usage examples into context.  Would we consider the option of ripping "##API" sections out of the readme?

**Comment by AdriVanHoudt** [comment]
Yeah I am also for a readme with api section, otherwise you will also lose all the info on the npm website

**Comment by hueniverse** [comment]
There is value is making people always go to the site instead of readmes. If someone wants to code this and make it work with readmes, I don't have any objections.

**Comment by AdriVanHoudt** [comment]
If it works with readme's it works with api.md right. I'll add it to my 'if I have free time' list

**Comment by nlf** [comment]
i prefer the idea of keeping the API docs in their own file. the site has github pre-render markdown content, which means if we were to use the README instead of API.md we would have to turn around and use cheerio or something to parse the rendered HTML to remove the content we don't want. that gets ugly pretty quick.

i vote keep it simple and add an API.md to all the plugins and just link to it in the README.md so it's still easily accessible

**Comment by AdriVanHoudt** [comment]
I follow @nlf on gitter "i think if the readme accurately describes the plugin’s purpose, and has a very clear link to api documentation, it should be fine"

**Comment by devinivy** [comment]
I imagined culling the markdown from the readme rather than culling the HTML.  It would pull from a section of with a standardized name (presumably, "API").  I'm concerned that especially for the smaller modules with simple APIs, this seeming small change that's being proposed will disproportionately discourage use (and ease-of-use).  I would feel more comfortable with it if a usage example were required in the readme.

**Comment by nlf** [comment]
a small usage example in the readme is a good idea, but i think the bulk of the documentation being in API.md makes the most sense.

**Comment by AdriVanHoudt** [comment]
there should be a template that module maintainers can copy and use for easiness
something like
```markdown
[logo]
[one liner from modules like `Node testing utility` for Lab]
# Name 

[build badge] [other badges]

Lead Maintainer: [name here]

[small intro here (can include usage example)]

For the full documentation of [module name] see **[api.md](API.md)**.
```

**Comment by hueniverse** [comment]
There are two options:

![image](https://user-images.githubusercontent.com/56631/39086420-b5c006f0-4545-11e8-9ffb-9584f3a0b7d1.png)

Above the current selectors or as new sections below. I think new sections make more sense but need to automagically pin the version of the module to the version of hapi selected based on the committed shrinkwrap file.

**Comment by Nargonath** [comment]
Alright, actually I was considering it as my next task.

**Comment by Nargonath** [comment]
What modules are we talking about? Is it only core modules or every module under hapijs organization?

**Comment by Nargonath** [comment]
I submitted a PR with the work I have done so far so you can check up how it looks. I think we'll need to  standardize the `API.md` format in the different projects. Some have summary at the beginning, some have not and I have no way of knowing at the moment which `ul` I should take or not when building the  links on the sidebar. For example, here is how the sidebar looks for `shot`:

![image](https://user-images.githubusercontent.com/583657/48973326-4371c180-f03d-11e8-8e22-bd623ac0e6cc.png)

It is the same for `topo` and `yar`.

Also once injected in the main section, the content does not look that good. For example, `good` `API.md` lacks a title mentioning the name of the project so you don't know what the content refers to.

**Comment by hueniverse** [comment]
What's the best way to standardize it?

**Comment by Nargonath** [comment]
@hueniverse I would say:
* Having a title repeating the name of the module because most of the `API.md` right now only have a title mentioning the version, which is ignored at the moment anyway.
* Either add an `ul` summary right after these titles pretty much as you have on `hapi` or `joi`. The main problem I see with that is for small modules like [`topo`](https://github.com/hapijs/topo/blob/master/API.md) where such _summary_ isn't really useful and just adds useless noise to the document. 
  * Another solution would be to add an html class to the generated `ul` resulting from the markdown list but I don't know if that's even doable. I'd have to dig into the lib used to generate the HTML from the markdown file to better assess.

That's the main problems I've noticed so far but there might be some more. I should have time to dedicate to this during the weekend so I'll fork some repos, play with the `API.md` in my forks and link the website to those repositories instead of the real ones to see how it goes. I should have more graphical results to show by then.

**Comment by Nargonath** [comment]
Alright I found a better solution for the problem I mentioned above. I updated my code on the PR. This is now fully functional. I'm sure people will want to tweak the CSS here and there so we'll just improve with feedbacks.

Some PRs I made to update `API.md` format are still pending approval:
- https://github.com/hapijs/hoek/pull/286
- https://github.com/hapijs/shot/pull/103

I don't have the rights to merge them myself. Can someone merge them please? I guess they require core team privileges. Once the PR are merged, I'll merge this feature as well.
