### ISSUE TITLE
Translation to Portuguese

### ISSUE THREAD

**Issue by alanleite** [hapijs/hapijs.com#292]
Hi guys,

Recently we the NodeBR Group translated the ExpressJS documentation to Portuguese. We would like to do the same for Hapi docs. How can we start this project?

Best,

**Comment by hueniverse** [comment]
That's tricky because the API docs are generated automatically from the hapi API.md file (same for all other hapi modules). Express rarely changes so it's practical to do that there, but we change the API on a weekly basis which means you will have very stale translations. I would suggest focusing on the tutorials and site in general first.

**Comment by alanleite** [comment]
I see...

If we going to starting the translation from tutorials, we will first work with 'lib/tutorials' files. 

First, fork the project and create /lib/tutorials/pt-BR, right?

After this we need to create a redirect on website for portuguese version.

I'm thinking the right way?

Best,

**Comment by hueniverse** [comment]
I'd leave the mechanics to @nlf

**Comment by nlf** [comment]
I think your hunch at a first jab is right on. Go ahead and fork and start translating and we'll sort out how to make it accessible :)

**Comment by alanleite** [comment]
Thank you
Let's make Hapi easy for Brazilian beginners!
We'll start the translations.
Best.

**Comment by alanleite** [comment]
We finished. And pull-request has been created.

**Comment by thebergamo** [comment]
This issue can be closed.

**Comment by vdeturckheim** [comment]
Closed by #408
