### ISSUE TITLE
a few questions from a new hapi user

### ISSUE THREAD

**Issue by pocketmax** [hapijs/hapijs.com#433]
I've read the docs and watched a few youtube presentations on hapi. I'm starting to truly see the power that hapi can provide over express (especially the unit testing). But I have a few questions on how I'm using it/how it should be used.
1. can plugins be registered with restricted access to the rest of your app? I noticed when I made a custom plugin and registered it with a prefixed route, the plugin could manipulate/see requests from other routes via server.ext and server.on. is that by design?
2. What is the general difference between realms, extensions and plugins. I’ve read a few docs and watched 2 very long youtube presentations but I’m still a little fuzzy on the differences and how each one should be used. i.e. using realms to partition an app for stability reasons so some parts of your app don’t change other parts of your app.
3. when I write a hello world plugin in a route config, it won’t work. What am I doing wrong? The docs say I can use a plugin config object, I thought thats what I did.

```
'use strict';
const Hapi = require('hapi');
const server = new Hapi.Server();
server
.connection({ port: 3000 })
.route({
    method: 'GET',
    path: '/testing',
    config: {
        plugins: {
            'foo': {
                register: function (server, options, next) {
                    console.log('foo plugin registered');
                    next();
                }
            }
        }
    },
    handler: function (request, reply) {
        reply('handler ran');
    }
});
server.start();
```
1. when I try to register a plugin to 2 routes, I get an error saying the plugin is already registered. Is that by design? Are plugins suppose to be singletons or is there a way to register a plugin with multiple routes? I read this post and a lot of it went over my head. https://github.com/hapijs/hapi/issues/2338

```
'use strict';

const Hapi = require('hapi');

const server = new Hapi.Server();
server
.connection({ port: 3000 })
.register({
    register: require('./stubplug'),
    routes: {
        prefix: '/foobar'
    },
}, (err) => {
    if (err) {
        throw err;
    }
});
server.register({
    register: require('./stubplug'),
    routes: {
        prefix: '/bla'
    },
}, (err) => {
    if (err) {
        throw err;
    }
});
server.start((err) => {
    if (err) {
        throw err;
    }
    console.log(`Server running at: ${server.info.uri}`);
});

```
1. is it possible to write a plugin that grabs a request, stores it so it can run later? I want to write a plugin that appends certain requests to a queue to be later executed by another server. At first glace, I could just copy the request object in the handler function but I wanted to see if there was a better way to do it.
2. I read somewhere that hapi uses node domains (which are pending deprecation) instead of try/catch. The reason is because domains allow you to fail gracefully from errors instead of exiting the app. When a forked process runs into an error, the process closes without closing the entire app. Is that the general reason why hapi uses domains over try/catch? Is there something I’m missing?
3. what is the difference between server.ext and server.on. I know server.ext does something with extensions and .on is for event handling. But I've been using server.ext for my event logic which I know isn't the proper way to do things.
4. Are plugins meant to have full exposure to the app or restricted sandboxed exposure only to child plugins registered in it? I’m trying to figure out the best practice for using plugins.

-thanks

**Comment by devinivy** [comment]
This is dense with many questions.  Rather than answering them all individually I will try to give you an impression of how all these concepts relate to each other and hopefully answer a few of your specific questions along the way :)

One hapi server may consist of several connections ([`server.connections`](https://github.com/hapijs/hapi/blob/master/API.md#serverconnections)), and plugins are registered to groups of connections using [`server.register()`](https://github.com/hapijs/hapi/blob/master/API.md#serverregisterplugins-options-callback).  Plugins act as a way to group bits functionality– typically they encompass a series of calls that you would make on a `server` object, such as adding routes with `server.route()` or request extensions with `server.ext()`.  Whatever happens inside a plugin only is applied to connections on the server to which the plugin is registered– that means a call to `server.route()` inside a plugin would add a route (or several) to each connection on `server.connections`.  In general you will register routes _within plugins_, and place those routes on connections by registering the plugin onto a server which has the desired connections.

Every time a plugin is registered it is given a "realm."  This realm is specific to one registration of one plugin– if the same plugin is registered to multiple hapi servers or registered twice to the same hapi server, each one will have a separate realm.  A realm is a place to read and write plugin-specific state.  This is essentially where plugin sandboxing takes place– for example, calls to [`server.bind()`](https://github.com/hapijs/hapi/blob/master/API.md#serverbindcontext) inside a plugin will only affect the current realm.  Much of the time what occurs in a plugin applies to entire connections, but when sandboxing does occur it's usually because realms are involved.  There are only a handful of cases that hapi uses realms for sandboxing (i.e. `server.bind()`, `server.path()`).  But realms are also available to you to sandbox plugin state that you're interested in tracking.  The vision plugin is a great example of this– in that case view managers are created and associated to a plugin registration using realms.  Realms are a useful concept, but it's not necessary to directly use them or think about them very often.

Server extensions [`server.ext()`](https://github.com/hapijs/hapi/blob/master/API.md#serverextevents) are a powerful tool used to hook into crucial steps in the lifecycle of your server (e.g. initializing, starting, stopping) or in the lifecycle of a request to one of `server`'s connections.  While request extensions typically apply to every request on a set of of connections, there is an option you can pass `{ sandbox: 'plugin' }` that will restrict the extension apply only to routes registered within the same plugin.  This is another form of sandboxing that does not rely directly on realms.  One important feature of extensions is that each one may specify whether it comes before or after extensions created by other plugins; this allows your extensions to run in a well-defined order, solving one problem you run into when using plain middleware (as in express).
