### ISSUE TITLE
Tutorials navigation cut off while scrolling

### ISSUE THREAD

**Issue by jkup** [hapijs/hapijs.com#449]
Hey,

I noticed that when scrolling through the https://hapijs.com/tutorials page on my macbook the bottom of the side nav gets cut off sometimes. I attached a GIF of what I'm seeing.

![hapi](https://cloud.githubusercontent.com/assets/490294/21292024/9dbb5f2a-c4bb-11e6-93da-3cc48ab67b7f.gif)

I think it's caused by:

<img width="290" alt="screen shot 2016-12-18 at 12 47 24 am" src="https://cloud.githubusercontent.com/assets/490294/21292023/99cb862e-c4bb-11e6-8b21-4d01dc09e09e.png">

**Comment by evanperriello** [comment]
Good spot. In Chrome, it gives you a scrollbar, but in Safari a lot of scrollbars won't display by default. And if the window height gets too small, the element eventually disappears. 

Adding a min-height to the nav (maybe of 350px or so) would keep it from getting too small, while still letting it shrink and scroll for smaller screens, and for Safari users, a -webkit-scrollbar-thumb property should make it more obvious that there are more links to be had in the nav, rather than just blanking them out. 

I'd be happy to play around and make a pull request for this, unless you wanted to take it yourself (I'm pretty new to open source projects, so I don't want to step on any toes). :)

**Comment by nlf** [comment]
if the issue hasn't been assigned to anyone, i wouldn't worry about stepping on toes :) any kind of pull request is appreciated and will be reviewed. worst we can do is say no thanks!

**Comment by AdriVanHoudt** [comment]
@evanperriello 🚀

**Comment by JustinBeaudry** [comment]
Looks like sticky nav for the sidebar has been removed. As such this seems to no longer be an issue. Any reason to keep this open @nlf?
