### ISSUE TITLE
Let's be polite

### ISSUE THREAD

**Issue by xuxogarcia** [hapijs/hapijs.com#539]
I was starting to be "happy" about using Hapi for an internal project and ran into an issue.
During my research, I came across someone else that had the same problem and confusion:

https://github.com/hapijs/hapi/issues/3697

The reply from @hueniverse was uncalled for, rude, and a strong reason to sway users away from Hapi.js. It represents an arrogance that gives projects like yours a bad name.

So disappointed. Moving on to a nicer group of folks that can help people that are new to something or willing to learn.

**Comment by nlf** [comment]
firstly, this is the wrong place to open any discussion. if you had yourself done any basic research you would see that discussion is all done in [the discuss repo](https://github.com/hapijs/discuss)

secondly, you opening an issue in the incorrect place just to tell us someone was rude in an issue in another repo is _no less_ uncalled for or rude.

thirdly, if you base your framework decisions on someone being told "don't be lazy" when they neglected to read documentation, i'm certain you're in for a good time where ever you look.

**Comment by hueniverse** [comment]
From @xuxogarcia:

> I was starting to be "happy" about using Hapi for an internal project and ran into an issue.
During my research, I came across someone else that had the same problem and confusion:

> hapijs/hapi#3697

> The reply from @hueniverse was uncalled for, rude, and a strong reason to sway users away from Hapi.js. It represents an arrogance that gives projects like yours a bad name.

> So disappointed. Moving on to a nicer group of folks that can help people that are new to something or willing to learn.

This is great. An issue titled "Let's be polite" and a descriptions that barely stops short of calling me an asshole. hapi is not just code, it is a community with a set of values and norms. Ignoring the detailed issue template and posting a questions that was asked before many times, just because one cannot be bothered to show respect for those maintaining the work is at best, laziness. Your commentary here shows the same lack of respect and an inflated sense of entitlement.

I know it's not pleasant getting called on in public but its absolutely necessary for the overall well-being of the project.

As for the "willing to learn" part, some of the people that acted similarly to the issue references reached out and explain what about the template and process was confusing. We also got feedback from people who are not native English speakers. As a result we put a lot of effort into making the issue template easier to understand and more explicit about what is the proper way to seek help. When people post these kind of issues in the core hapi module we simply close the issue, lock it, and label it with `missing discussion` as clearly stated in the template.

You might consider opening random questions an acceptable behavior (and it is indeed how many people behave elsewhere), but it is extremely rude. Every hapi ecosystem module has multiple people who volunteer their time maintaining it. When you post a question, all these people have to read it and deal with it - even if that means ignoring it and letting someone else respond. This can take 10-20 minutes each day for someone like me that monitors dozens of hapi.js modules.

To make this process work for everyone, we created a discussion repo and linked to it from multiple places. We created an issue template that is clear and detailed. And we left behind a trail of similar issues that got stern responses for breaking the rules.

If after all that, you still choose to post questions in the wrong place, actively ignoring the instructions and erasing them to write your question, then, who's the asshole now?
